// Generated by https://quicktype.io

export interface ApiResponseError {
	code: number;
	message: string;
}

export interface ApiResponseSuccess<TData extends undefined | object> {
	code: number;
	message: string;
	data: TData;
}

export type ApiPaginatedResponseSuccess<TData> = ApiResponseSuccess<
	ApiPaginated<TData>
>;

export interface ApiPaginated<TData> {
	total: number;
	per_page: number;
	current_page: number;
	last_page: number;
	first_page_url: string;
	last_page_url: string;
	next_page_url: string;
	prev_page_url: null;
	from: number;
	path: string;
	to: number;
	items?: TData[];
	data?: TData[];
}

export interface ApiPaginatedRequest {
	per_page: number;
	page: number;
}
