export const ADMIN_ROUTE_PREFIX = '/admin' as const;

const ADMIN_ARTICLES_ROUTE_PREFIX = '/admin/article';
const ADMIN_MANAGEMENT_USERS_ROUTES_PREFIX = '/admin/users-management';

const ADMIN_ARTICLES_ROUTE = {
	ARTICLES: ADMIN_ARTICLES_ROUTE_PREFIX,
	ARTICLES_DETAIL: `${ADMIN_ARTICLES_ROUTE_PREFIX}/detail`,
	ARTICLES_CREATE: `${ADMIN_ARTICLES_ROUTE_PREFIX}/create`,
} as const;

const ADMIN_MANAGEMENT_USERS_ROUTE = {
	USERS: ADMIN_MANAGEMENT_USERS_ROUTES_PREFIX,
	USERS_DETAIL: `${ADMIN_MANAGEMENT_USERS_ROUTES_PREFIX}/detail`,
	USERS_CREATE: `${ADMIN_MANAGEMENT_USERS_ROUTES_PREFIX}/create`,
} as const;

export const ADMIN_ROUTES = {
	DASHBOARD: ADMIN_ROUTE_PREFIX + '/dashboard',
	...ADMIN_ARTICLES_ROUTE,
	...ADMIN_MANAGEMENT_USERS_ROUTE,
} as const;
