export const USER_ROUTE_PREFIX = '/user' as const;

const USER_ARTICLES_ROUTE_PREFIX = '/user/article';
const USER_MY_ARTICLES_ROUTE_PREFIX = '/user/my-article';

const USER_ARTICLES_ROUTE = {
	ARTICLES: USER_ARTICLES_ROUTE_PREFIX,
	ARTICLES_DETAIL: `${USER_ARTICLES_ROUTE_PREFIX}/detail`,
} as const;

const USER_MY_ARTICLES_ROUTE = {
	MY_ARTICLES: USER_MY_ARTICLES_ROUTE_PREFIX,
	MY_ARTICLES_DETAIL: `${USER_MY_ARTICLES_ROUTE_PREFIX}/detail`,
	MY_ARTICLES_CREATE: `${USER_MY_ARTICLES_ROUTE_PREFIX}/create`,
} as const;

export const USER_ROUTES = {
	DASHBOARD: USER_ROUTE_PREFIX + '/dashboard',
	...USER_ARTICLES_ROUTE,
	...USER_MY_ARTICLES_ROUTE,
} as const;
